name: flutter_quick_start
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # fluro(Null safety) - https://pub.flutter-io.cn/packages/fluro
  fluro: ^2.0.3
  # shared_preferences(Null safety)https://pub.flutter-io.cn/packages/shared_preferences
  shared_preferences: ^2.0.5
  # logger(Null safety) - https://pub.flutter-io.cn/packages/logger
  logger: ^1.0.0-nullsafety.0
  # toast(Null safety) - https://pub.flutter-io.cn/packages/fluttertoast
  fluttertoast: ^8.0.1-nullsafety.0
  # dio(Null safety) - https://pub.flutter-io.cn/packages/dio
  dio: ^4.0.0-beta7
  # device_info(Null safety)  - https://pub.flutter-io.cn/packages/device_info
  device_info: ^2.0.0
  # webview_flutter(Null safety) - https://pub.flutter-io.cn/packages/webview_flutter
  webview_flutter: ^2.0.2
  # permission_handler(Null safety) - https://pub.flutter-io.cn/packages/permission_handler
  permission_handler: ^6.1.0
  # back_button_interceptor(Null safety) - https://pub.flutter-io.cn/packages/back_button_interceptor
  back_button_interceptor: ^5.0.0
  # flutter_easyloading(Null safety) - https://pub.flutter-io.cn/packages/flutter_easyloading
  flutter_easyloading: ^3.0.0
  # shimmer(Null safety) - https://pub.flutter-io.cn/packages/shimmer
  shimmer: ^2.0.0-nullsafety.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - locale/
    - assets/images/
    - assets/test.html
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
