name: flutter_quick_start
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter
  provider: ^6.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # shared_preferences(Null safety)https://pub.flutter-io.cn/packages/shared_preferences
  shared_preferences: ^2.0.15
  # logger(Null safety) - https://pub.flutter-io.cn/packages/logger
  logger: ^1.1.0
  # toast(Null safety) - https://pub.flutter-io.cn/packages/flutter_styled_toast
  flutter_styled_toast: ^2.1.3
  # dio(Null safety) - https://pub.flutter-io.cn/packages/dio
  dio: ^4.0.6
  # device_info_plus(Null safety)  - https://pub.flutter-io.cn/packages/device_info_plus
  device_info_plus: ^3.2.3
  # webview_flutter(Null safety) - https://pub.flutter-io.cn/packages/webview_flutter
  webview_flutter: ^3.0.4
  # permission_handler(Null safety) - https://pub.flutter-io.cn/packages/permission_handler
  permission_handler: ^9.2.0
  # back_button_interceptor(Null safety) - https://pub.flutter-io.cn/packages/back_button_interceptor
  back_button_interceptor: ^6.0.0
  # flutter_easyloading(Null safety) - https://pub.flutter-io.cn/packages/flutter_easyloading
  flutter_easyloading: ^3.0.3
  # shimmer(Null safety) - https://pub.flutter-io.cn/packages/shimmer
  shimmer: ^2.0.0
  # flutter_hooks - https://pub.flutter-io.cn/packages/flutter_hooks
  flutter_hooks: ^0.18.4
  # flutter_screenutil - https://pub.dev/packages/flutter_screenutil
  # flutter_screenutil: ^5.5.4
  # https://pub.dev/packages/easy_localization
  easy_localization: ^3.0.1
  # https://pub.flutter-io.cn/packages/get_it
  get_it: ^7.2.0
  # https://pub.flutter-io.cn/packages/get_it
  get_it_mixin: ^3.1.4
  # https://pub.flutter-io.cn/packages/go_router
  go_router: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
  flutter_lints: ^2.0.0
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/locale/
    - assets/images/
    - assets/images/tab/
    - assets/test.html

  fonts:
      - family: Tenor
        fonts:
          - asset: assets/fonts/TenorSans-Regular.ttf
      - family: Raleway
        fonts:
          - asset: assets/fonts/Raleway-Regular.ttf
          - asset: assets/fonts/Raleway-Italic.ttf
            style: italic
          - asset: assets/fonts/Raleway-Medium.ttf
            weight: 500
          - asset: assets/fonts/Raleway-Bold.ttf
            weight: 700
          - asset: assets/fonts/Raleway-ExtraBold.ttf
            weight: 800
